trigger:
- main

pool:
  name: Default   # self-hosted agent

steps:
- script: docker --version
  displayName: 'Check Docker'

- script: |
    docker build -t portfolio-app:ci .
  displayName: 'Build Docker image'

- script: docker images
  displayName: 'List Docker images'
